### ISSUE TITLE
StringIndexOutOfBoundsException with {@}

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#515]
In a new qute template, when you start with {@}, you get this exception in the logs:

```
SEVERE: Error while validating 'file:///Users/fbricon/Dev/souk/quarkus-vuln/src/main/resources/templates/truc.qute.html'.
java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at io.quarkus.qute.Parser.flushTag(Parser.java:480)
	at io.quarkus.qute.Parser.tag(Parser.java:293)
	at io.quarkus.qute.Parser.processCharacter(Parser.java:200)
	at io.quarkus.qute.Parser.parse(Parser.java:132)
	at io.quarkus.qute.EngineImpl.parse(EngineImpl.java:56)
	at io.quarkus.qute.Engine.parse(Engine.java:30)
	at com.redhat.qute.services.QuteDiagnostics.validateWithRealQuteParser(QuteDiagnostics.java:181)
	at com.redhat.qute.services.QuteDiagnostics.doDiagnostics(QuteDiagnostics.java:165)
	at com.redhat.qute.services.QuteLanguageService.doDiagnostics(QuteLanguageService.java:140)
	at com.redhat.qute.ls.template.TemplateFileTextDocumentService.lambda$triggerValidationFor$22(TemplateFileTextDocumentService.java:254)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at com.redhat.qute.ls.template.TemplateFileTextDocumentService.triggerValidationFor(TemplateFileTextDocumentService.java:246)
	at com.redhat.qute.ls.template.TemplateFileTextDocumentService.lambda$triggerValidationFor$21(TemplateFileTextDocumentService.java:272)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at com.redhat.qute.ls.commons.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:148)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)



```

**Comment by angelozerr** [comment]
It's a bug with real Qute parser /cc @mkouba .

**Comment by mkouba** [comment]
What version of quarkus do you use? This should be fixed in 2.5.2.Final. See https://github.com/quarkusio/quarkus/pull/21947

**Comment by fbricon** [comment]
I was using 2.5.0.Final. However updating to 2.5.2.Final didn't fix it. @angelozerr is quarkus-ls embedding its own version of the qute parser?

**Comment by angelozerr** [comment]
> This should be fixed in 2.5.2.Final. See quarkusio/quarkus#21947

My bad, sorry @mkouba I forget that you fixed it, sorry -(

> . @angelozerr is quarkus-ls embedding its own version of the qute parser?

Yes for the moment, but my idea is to download the Qute Jar from the project dependency and cosnume Qute parser with Jav areflection.

**Comment by angelozerr** [comment]
>  @angelozerr is quarkus-ls embedding its own version of the qute parser?

I created an issue for that at https://github.com/redhat-developer/quarkus-ls/issues/521
